// docs/blocks/examples/svelte/ListingBlock.svelte
<script>
  export let block;
  export let blockId;

  let items = [];

  $: block.querystring, loadItems();

  async function loadItems() {
    const result = await expandListingBlocks(
      { [blockId]: block },
      [blockId],
      blockId,
    );
    items = result.items;
  }
</script>

<div data-block-uid={blockId} class="listing-block">
  {#each items as item (item['@uid'])}
    <div data-block-uid={item['@uid']} class="listing-item">
      {#if block.variation === 'summary' && item.image}
        <img src={item.image} alt="" />
      {/if}
      <h3><a href={item.href}>{item.title}</a></h3>
      <p>{item.description}</p>
    </div>
  {/each}
</div>

// docs/blocks/examples/vue/ListingBlock.vue
<template>
  <div :data-block-uid="blockId" class="listing-block">
    <div v-for="item in items" :key="item['@uid']" :data-block-uid="item['@uid']" class="listing-item">
      <img v-if="block.variation === 'summary' && item.image" :src="item.image" alt="" />
      <h3><a :href="item.href">{{ item.title }}</a></h3>
      <p>{{ item.description }}</p>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue';

const props = defineProps({ block: Object, blockId: String });
const items = ref([]);

watch(() => props.block.querystring, async () => {
  const result = await expandListingBlocks(
    { [props.blockId]: props.block },
    [props.blockId],
    props.blockId,
  );
  items.value = result.items;
}, { immediate: true });
</script>
