// docs/blocks/examples/svelte/BlockRenderer.svelte
<script>
  import SlateBlock from './SlateBlock.svelte';
  import IntroductionBlock from './IntroductionBlock.svelte';
  import ImageBlock from './ImageBlock.svelte';
  import HeroBlock from './HeroBlock.svelte';
  import TeaserBlock from './TeaserBlock.svelte';
  import TableBlock from './TableBlock.svelte';
  import ColumnsBlock from './ColumnsBlock.svelte';
  import GridBlock from './GridBlock.svelte';
  import AccordionBlock from './AccordionBlock.svelte';
  import SliderBlock from './SliderBlock.svelte';
  import ListingBlock from './ListingBlock.svelte';
  import SearchBlock from './SearchBlock.svelte';
  import FormBlock from './FormBlock.svelte';
  import HeadingBlock from './HeadingBlock.svelte';
  import SeparatorBlock from './SeparatorBlock.svelte';
  import ButtonBlock from './ButtonBlock.svelte';
  import HighlightBlock from './HighlightBlock.svelte';
  import VideoBlock from './VideoBlock.svelte';
  import TocBlock from './TocBlock.svelte';

  export let block;
</script>

{#if block['@type'] === 'slate'}
  <SlateBlock {block} />
{:else if block['@type'] === 'introduction'}
  <IntroductionBlock {block} />
{:else if block['@type'] === 'image'}
  <ImageBlock {block} />
{:else if block['@type'] === 'hero'}
  <HeroBlock {block} />
{:else if block['@type'] === 'teaser'}
  <TeaserBlock {block} />
{:else if block['@type'] === 'slateTable'}
  <TableBlock {block} />
{:else if block['@type'] === 'columns'}
  <ColumnsBlock {block} />
{:else if block['@type'] === 'gridBlock'}
  <GridBlock {block} />
{:else if block['@type'] === 'accordion'}
  <AccordionBlock {block} />
{:else if block['@type'] === 'slider'}
  <SliderBlock {block} />
{:else if block['@type'] === 'listing'}
  <ListingBlock {block} blockId={block['@uid']} />
{:else if block['@type'] === 'search'}
  <SearchBlock {block} blockId={block['@uid']} />
{:else if block['@type'] === 'form'}
  <FormBlock {block} />
{:else if block['@type'] === 'heading'}
  <HeadingBlock {block} />
{:else if block['@type'] === 'separator'}
  <SeparatorBlock {block} />
{:else if block['@type'] === '__button'}
  <ButtonBlock {block} />
{:else if block['@type'] === 'highlight'}
  <HighlightBlock {block} />
{:else if block['@type'] === 'video'}
  <VideoBlock {block} />
{:else if block['@type'] === 'toc'}
  <TocBlock {block} />
{:else}
  <div data-block-uid={block['@uid']}>Unknown block: {block['@type']}</div>
{/if}

// docs/blocks/examples/react/BlockRenderer.jsx
function BlockRenderer({ block }) {
  const type = block['@type'];
  switch (type) {
    case 'slate':         return <SlateBlock block={block} />;
    case 'introduction':  return <IntroductionBlock block={block} />;
    case 'image':         return <ImageBlock block={block} />;
    case 'hero':          return <HeroBlock block={block} />;
    case 'teaser':        return <TeaserBlock block={block} />;
    case 'slateTable':    return <TableBlock block={block} />;
    case 'columns':       return <ColumnsBlock block={block} />;
    case 'gridBlock':     return <GridBlock block={block} />;
    case 'accordion':     return <AccordionBlock block={block} />;
    case 'slider':        return <SliderBlock block={block} />;
    case 'listing':       return <ListingBlock block={block} blockId={block['@uid']} />;
    case 'search':        return <SearchBlock block={block} blockId={block['@uid']} />;
    case 'form':          return <FormBlock block={block} />;
    case 'heading':       return <HeadingBlock block={block} />;
    case 'separator':     return <SeparatorBlock block={block} />;
    case '__button':      return <ButtonBlock block={block} />;
    case 'highlight':     return <HighlightBlock block={block} />;
    case 'video':         return <VideoBlock block={block} />;
    case 'toc':           return <TocBlock block={block} />;
    default:              return <div data-block-uid={block['@uid']}>Unknown block: {type}</div>;
  }
}
