// docs/blocks/examples/vue/GridBlock.vue
<template>
  <div :data-block-uid="id" class="grid-block">
    <div :style="{ display: 'grid', gridTemplateColumns: `repeat(${columns.length}, 1fr)`, gap: '1rem' }">
      <div v-for="col in columns" :key="col['@id']" :data-block-uid="col['@id']" class="grid-column">
        <Block v-for="item in expand(col.blocks_layout?.items || [], col.blocks, col['@id'])"
          :key="item['@uid']" :data="item" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { expandListingBlocks } from '@hydra-js/hydra.js';
const props = defineProps({ block: Object, id: String });
const columns = computed(() => props.block.columns || []);
function expand(layout, blocks, containerId) {
  return expandListingBlocks(layout, { blocks, containerId });
}
</script>

// docs/blocks/examples/react/GridBlock.jsx
import { expandListingBlocks } from '@hydra-js/hydra.js';

function GridBlock({ block, blockId }) {
  const columns = block.columns || [];

  function expand(layout, blocks, containerId) {
    return expandListingBlocks(layout, { blocks, containerId });
  }

  return (
    <div data-block-uid={blockId} className="grid-block">
      <div style={{ display: 'grid', gridTemplateColumns: `repeat(${columns.length}, 1fr)`, gap: '1rem' }}>
        {columns.map(col => {
          const items = expand(col.blocks_layout?.items || [], col.blocks, col['@id']);
          return (
            <div key={col['@id']} data-block-uid={col['@id']} className="grid-column">
              {items.map(item => (
                <BlockRenderer key={item['@uid']} block={item} />
              ))}
            </div>
          );
        })}
      </div>
    </div>
  );
}
