// docs/blocks/examples/vue/HighlightBlock.vue
<template>
  <section
    :data-block-uid="block['@uid']"
    class="highlight-block"
    :style="{ backgroundImage: block.image ? `url(${block.image})` : undefined }"
  >
    <div class="highlight-overlay">
      <h2 data-edit-text="title">{{ block.title }}</h2>
      <div class="highlight-body">
        <SlateNode v-for="(node, i) in block.description || []" :key="i" :node="node" />
      </div>
      <a
        v-if="block.cta_title"
        :href="ctaLink"
        data-edit-text="cta_title"
        data-edit-link="cta_link"
        class="highlight-cta"
      >
        {{ block.cta_title }}
      </a>
    </div>
  </section>
</template>

<script setup>
import { computed } from 'vue';
const props = defineProps({ block: Object });
const ctaLink = computed(() => props.block.cta_link?.[0]?.['@id'] || '');
</script>

// docs/blocks/examples/react/HighlightBlock.jsx
function HighlightBlock({ block }) {
  const title = block.title || '';
  const description = block.description || [];
  const imageSrc = block.image || '';
  const ctaText = block.cta_title || '';
  const ctaLink = block.cta_link?.[0]?.['@id'] || '';

  return (
    <section
      data-block-uid={block['@uid']}
      className="highlight-block"
      style={{ backgroundImage: imageSrc ? `url(${imageSrc})` : undefined }}
    >
      <div className="highlight-overlay">
        <h2 data-edit-text="title">{title}</h2>
        <div className="highlight-body">
          {description.map((node, i) => (
            <SlateNode key={i} node={node} />
          ))}
        </div>
        {ctaText && (
          <a href={ctaLink} data-edit-text="cta_title" data-edit-link="cta_link" className="highlight-cta">
            {ctaText}
          </a>
        )}
      </div>
    </section>
  );
}
