// docs/blocks/examples/svelte/ImageBlock.svelte
<script>
  export let block;
  $: href = block.href?.[0]?.['@id'] || block.href;
</script>

<div data-block-uid={block['@uid']}>
  {#if href}
    <a {href} data-edit-link="href">
      <img data-edit-media="url" src={block.url} alt={block.alt} />
    </a>
  {:else}
    <img data-edit-media="url" src={block.url} alt={block.alt} />
  {/if}
</div>

// docs/blocks/examples/react/ImageBlock.jsx
function ImageBlock({ block }) {
  const src = block.url || '';
  const alt = block.alt || '';
  const href = block.href?.[0]?.['@id'] || block.href;

  const img = (
    <img data-edit-media="url" src={src} alt={alt} />
  );

  return (
    <div data-block-uid={block['@uid']}>
      {href ? (
        <a href={href} data-edit-link="href">{img}</a>
      ) : (
        <>{img}</>
      )}
    </div>
  );
}
