// docs/blocks/examples/svelte/IntroductionBlock.svelte
<script>
  import SlateNode from './SlateNode.svelte';
  export let block;
</script>

<div data-block-uid={block['@uid']} class="introduction-block">
  <div class="introduction-body" data-edit-text="value">
    {#each block.value || [] as node, i (i)}
      <SlateNode {node} />
    {/each}
  </div>
</div>

// docs/blocks/examples/react/IntroductionBlock.jsx
function IntroductionBlock({ block }) {
  return (
    <div data-block-uid={block['@uid']} className="introduction-block">
      <div className="introduction-body" data-edit-text="value">
        {(block.value || []).map((node, i) => (
          <SlateNode key={i} node={node} />
        ))}
      </div>
    </div>
  );
}
