// docs/blocks/examples/vue/IntroductionBlock.vue
<template>
  <div :data-block-uid="block['@uid']" class="introduction-block">
    <h1 data-edit-text="/title">{{ content.title }}</h1>
    <p v-if="content.description" data-edit-text="/description" class="description">{{ content.description }}</p>
  </div>
</template>

<script setup>
defineProps({ block: Object, content: Object });
</script>

// docs/blocks/examples/react/IntroductionBlock.jsx
function IntroductionBlock({ block, content }) {
  return (
    <div data-block-uid={block['@uid']} className="introduction-block">
      <h1 data-edit-text="/title">{content.title}</h1>
      {content.description && <p data-edit-text="/description" className="description">{content.description}</p>}
    </div>
  );
}
