// docs/examples/examples/vue/IntroductionBlock.vue
<template>
  <div :data-block-uid="block['@uid']" class="introduction-block">
    <div class="introduction-body" data-edit-text="value">
      <SlateNode v-for="(node, i) in block.value || []" :key="i" :node="node" />
    </div>
  </div>
</template>

<script setup>
import SlateNode from './SlateNode.vue';
defineProps({ block: Object });
</script>

// docs/blocks/examples/react/IntroductionBlock.jsx
function IntroductionBlock({ block }) {
  return (
    <div data-block-uid={block['@uid']} className="introduction-block">
      <div className="introduction-body" data-edit-text="value">
        {(block.value || []).map((node, i) => (
          <SlateNode key={i} node={node} />
        ))}
      </div>
    </div>
  );
}
