// docs/examples/test-react/src/App.jsx
import React from 'react';
import BlockRenderer from '$examples/BlockRenderer.jsx';

export default function App({ items, content }) {
  return (
    <div id="content">
      {items.map(block => (
        <BlockRenderer key={block['@uid']} block={block} content={content} />
      ))}
    </div>
  );
}

// docs/blocks/test-vue/src/App.vue
<template>
  <div id="content">
    <BlockRenderer v-for="block in items" :key="block['@uid']" :block="block" :content="content" />
  </div>
</template>

<script setup>
import BlockRenderer from '$examples/BlockRenderer.vue';

defineProps({
  items: { type: Array, default: () => [] },
  content: { type: Object, default: () => ({}) },
});
</script>
