// docs/examples/examples/vue/BlockRenderer.vue
<template>
  <component :is="componentFor(block['@type'])" :block="block" :blockId="block['@uid']" :content="content" />
</template>

<script setup>
import { getImageUrl } from './utils.js';
import SlateBlock from './SlateBlock.vue';
import IntroductionBlock from './IntroductionBlock.vue';
import ImageBlock from './ImageBlock.vue';
import HeroBlock from './HeroBlock.vue';
import TeaserBlock from './TeaserBlock.vue';
import TableBlock from './TableBlock.vue';
import ColumnsBlock from './ColumnsBlock.vue';
import GridBlock from './GridBlock.vue';
import AccordionBlock from './AccordionBlock.vue';
import SliderBlock from './SliderBlock.vue';
import ListingBlock from './ListingBlock.vue';
import SearchBlock from './SearchBlock.vue';
import FormBlock from './FormBlock.vue';
import HeadingBlock from './HeadingBlock.vue';
import SeparatorBlock from './SeparatorBlock.vue';
import ButtonBlock from './ButtonBlock.vue';
import HighlightBlock from './HighlightBlock.vue';
import CalloutBlock from './CalloutBlock.vue';
import VideoBlock from './VideoBlock.vue';
import MapsBlock from './MapsBlock.vue';
import TocBlock from './TocBlock.vue';
import CodeExampleBlock from './CodeExampleBlock.vue';
import CookieConsentBlock from './CookieConsentBlock.vue';
import { h } from 'vue';

defineProps({ block: Object, blockId: String, content: Object });

const ListingItemBlock = {
  props: ['block'],
  render() {
    const b = this.block;
    const imgSrc = getImageUrl(b.image);
    return h('div', { 'data-block-uid': b['@uid'], class: 'listing-item' }, [
      imgSrc ? h('img', { src: imgSrc, alt: '', 'data-edit-media': 'image' }) : null,
      b.date ? h('time', { style: 'font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em' }, new Date(b.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })) : null,
      h('h4', null, [h('a', { href: contentPath(b.href), 'data-edit-link': 'href' }, b.title)]),
      b.description ? h('p', { 'data-edit-text': 'description' }, b.description) : null,
    ]);
  },
};

const typeMap = {
  slate: SlateBlock,
  introduction: IntroductionBlock,
  image: ImageBlock,
  hero: HeroBlock,
  teaser: TeaserBlock,
  slateTable: TableBlock,
  columns: ColumnsBlock,
  gridBlock: GridBlock,
  accordion: AccordionBlock,
  slider: SliderBlock,
  listing: ListingBlock,
  search: SearchBlock,
  form: FormBlock,
  heading: HeadingBlock,
  separator: SeparatorBlock,
  button: ButtonBlock,
  highlight: HighlightBlock,
  callout: CalloutBlock,
  video: VideoBlock,
  maps: MapsBlock,
  toc: TocBlock,
  codeExample: CodeExampleBlock,
  cookieConsent: CookieConsentBlock,
  summary: ListingItemBlock,
  default: ListingItemBlock,
};

function componentFor(type) {
  return typeMap[type] || {
    props: ['block'],
    render() {
      return h('div', { 'data-block-uid': this.block['@uid'], 'data-unknown-block-type': type }, '[not implemented]');
    },
  };
}
</script>

// docs/examples/examples/svelte/BlockRenderer.svelte
<script>
  import { getImageUrl } from './utils.js';
  import SlateBlock from './SlateBlock.svelte';
  import IntroductionBlock from './IntroductionBlock.svelte';
  import ImageBlock from './ImageBlock.svelte';
  import HeroBlock from './HeroBlock.svelte';
  import TeaserBlock from './TeaserBlock.svelte';
  import TableBlock from './TableBlock.svelte';
  import ColumnsBlock from './ColumnsBlock.svelte';
  import GridBlock from './GridBlock.svelte';
  import AccordionBlock from './AccordionBlock.svelte';
  import SliderBlock from './SliderBlock.svelte';
  import ListingBlock from './ListingBlock.svelte';
  import SearchBlock from './SearchBlock.svelte';
  import FormBlock from './FormBlock.svelte';
  import HeadingBlock from './HeadingBlock.svelte';
  import SeparatorBlock from './SeparatorBlock.svelte';
  import ButtonBlock from './ButtonBlock.svelte';
  import HighlightBlock from './HighlightBlock.svelte';
  import CalloutBlock from './CalloutBlock.svelte';
  import VideoBlock from './VideoBlock.svelte';
  import MapsBlock from './MapsBlock.svelte';
  import TocBlock from './TocBlock.svelte';
  import CodeExampleBlock from './CodeExampleBlock.svelte';
  import CookieConsentBlock from './CookieConsentBlock.svelte';

  export let block;
  export let content = {};
</script>

{#if block['@type'] === 'slate'}
  <SlateBlock {block} />
{:else if block['@type'] === 'introduction'}
  <IntroductionBlock {block} {content} />
{:else if block['@type'] === 'image'}
  <ImageBlock {block} />
{:else if block['@type'] === 'hero'}
  <HeroBlock {block} />
{:else if block['@type'] === 'teaser'}
  <TeaserBlock {block} />
{:else if block['@type'] === 'slateTable'}
  <TableBlock {block} />
{:else if block['@type'] === 'columns'}
  <ColumnsBlock {block} />
{:else if block['@type'] === 'gridBlock'}
  <GridBlock {block} />
{:else if block['@type'] === 'accordion'}
  <AccordionBlock {block} />
{:else if block['@type'] === 'slider'}
  <SliderBlock {block} />
{:else if block['@type'] === 'listing'}
  <ListingBlock {block} blockId={block['@uid']} />
{:else if block['@type'] === 'search'}
  <SearchBlock {block} blockId={block['@uid']} />
{:else if block['@type'] === 'form'}
  <FormBlock {block} />
{:else if block['@type'] === 'heading'}
  <HeadingBlock {block} />
{:else if block['@type'] === 'separator'}
  <SeparatorBlock {block} />
{:else if block['@type'] === 'button'}
  <ButtonBlock {block} />
{:else if block['@type'] === 'highlight'}
  <HighlightBlock {block} />
{:else if block['@type'] === 'callout'}
  <CalloutBlock {block} />
{:else if block['@type'] === 'video'}
  <VideoBlock {block} />
{:else if block['@type'] === 'maps'}
  <MapsBlock {block} />
{:else if block['@type'] === 'toc'}
  <TocBlock {block} {content} />
{:else if block['@type'] === 'cookieConsent'}
  <CookieConsentBlock {block} />
{:else if block['@type'] === 'codeExample'}
  <CodeExampleBlock {block} />
{:else if block['@type'] === 'summary' || block['@type'] === 'default'}
  <div data-block-uid={block['@uid']} class="listing-item">
    {#if block.image}
      {#if getImageUrl(block.image)}<img data-edit-media="image" src={getImageUrl(block.image)} alt="" />{/if}
    {/if}
    {#if block.date}<time style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em">{new Date(block.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</time>{/if}
    <h4><a href={contentPath(block.href)} data-edit-link="href">{block.title}</a></h4>
    {#if block.description}<p data-edit-text="description">{block.description}</p>{/if}
  </div>
{:else}
  <div data-block-uid={block['@uid']} data-unknown-block-type={block['@type']}>[not implemented]</div>
{/if}
