// docs/examples/examples/vue/CookieConsentBlock.vue
<template>
  <!--
    A block drawn in three places, two of them hidden.

    The block's own element is the bar; its `message` is read in a BANNER at the
    foot of the page and its `analyticsPurpose` beside a tick box in a
    PREFERENCES DIALOG. Both are teleported to <body> — where a design system's
    own JavaScript would put them — and both are hidden until their trigger is
    pressed. So "is the block visible?" is the wrong question, and each trigger
    names the FIELD its half holds instead.
  -->
  <div :data-block-uid="block['@uid']" class="cookie-consent">
    <div class="cookie-consent__bar">
      <strong>Cookie consent</strong>
      <!-- "I reveal where `message` is edited": focusing Banner message in the
           sidebar makes the bridge click this, so the banner is on screen while
           its wording is written. -->
      <button type="button"
        :data-block-selector="`${block['@uid']}#message`"
        @click="showBanner = true">Show the banner</button>
      <!-- The other half. One handle is one click, so a block-level handle
           could only ever open one of the two. -->
      <button type="button"
        :data-block-selector="`${block['@uid']}#analyticsPurpose`"
        @click="showDialog = true">Show cookie preferences</button>
    </div>

    <!-- Both halves live outside this block's DOM, so their editable text is
         annotated where it is READ. -->
    <Teleport to="body">
      <div class="cookie-banner" :hidden="!showBanner" role="alert">
        <p data-edit-text="message">{{ slateToText(block.message) }}</p>
        <button type="button" @click="showBanner = false">Accept all</button>
        <button type="button" @click="showDialog = true">Manage preferences</button>
      </div>
      <div class="cookie-dialog" :hidden="!showDialog" role="dialog">
        <h2>Manage cookie preferences</h2>
        <label><input type="checkbox" name="analytics" /> Analytics</label>
        <p data-edit-text="analyticsPurpose">{{ block.analyticsPurpose }}</p>
        <button type="button" @click="showDialog = false">Save</button>
      </div>
    </Teleport>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const props = defineProps({ block: Object });
const showBanner = ref(true);
const showDialog = ref(false);

// Slate is an array of nodes; the banner shows its text. A real frontend would
// render the marks and links too — kept flat here so the pattern stays visible.
function slateToText(value) {
  if (!Array.isArray(value)) return '';
  return value
    .map((node) => node.text ?? (node.children || []).map((c) => c.text ?? '').join(''))
    .join('');
}
</script>

// docs/examples/examples/svelte/CookieConsentBlock.svelte
<script>
  // A block drawn in three places, two of them hidden. The bar is the block's
  // own element; `message` is read in a banner at the foot of the page and
  // `analyticsPurpose` beside a tick box in a preferences dialog, both hidden
  // until their trigger is pressed. Each trigger names the FIELD its half holds,
  // because one block-level handle is one click and could open only one of them.
  export let block;

  let showBanner = true;
  let showDialog = false;

  // Slate is an array of nodes; the banner shows its text.
  function slateToText(value) {
    if (!Array.isArray(value)) return '';
    return value
      .map((node) => node.text ?? (node.children || []).map((c) => c.text ?? '').join(''))
      .join('');
  }
</script>

<div data-block-uid={block['@uid']} class="cookie-consent">
  <div class="cookie-consent__bar">
    <strong>Cookie consent</strong>
    <button type="button"
      data-block-selector={`${block['@uid']}#message`}
      on:click={() => (showBanner = true)}>Show the banner</button>
    <button type="button"
      data-block-selector={`${block['@uid']}#analyticsPurpose`}
      on:click={() => (showDialog = true)}>Show cookie preferences</button>
  </div>
</div>

<!-- Svelte renders these where they are written; a real frontend would portal
     them to <body>, as the React and Vue examples do. What matters for the
     pattern is that they are OUTSIDE the block's element and hidden. -->
<div class="cookie-banner" hidden={!showBanner} role="alert">
  <p data-edit-text="message">{slateToText(block.message)}</p>
  <button type="button" on:click={() => (showBanner = false)}>Accept all</button>
  <button type="button" on:click={() => (showDialog = true)}>Manage preferences</button>
</div>

<div class="cookie-dialog" hidden={!showDialog} role="dialog">
  <h2>Manage cookie preferences</h2>
  <label><input type="checkbox" name="analytics" /> Analytics</label>
  <p data-edit-text="analyticsPurpose">{block.analyticsPurpose}</p>
  <button type="button" on:click={() => (showDialog = false)}>Save</button>
</div>
