// docs/blocks/examples/vue/TocBlock.vue
<template>
  <nav :data-block-uid="block['@uid']" class="toc-block">
    <ul v-if="entries.length">
      <li v-for="e in entries" :key="e.id" :style="{ marginLeft: (e.level - 2) * 1.5 + 'em' }">
        <a :href="`#${e.id}`">{{ e.text }}</a>
      </li>
    </ul>
    <p v-else>Table of Contents</p>
  </nav>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({ block: Object, content: Object });

const entries = computed(() => {
  const result = [];
  const c = props.content;
  if (!c?.blocks || !c?.blocks_layout?.items) return result;
  for (const id of c.blocks_layout.items) {
    const b = c.blocks[id];
    if (!b) continue;
    if (b['@type'] === 'heading' && b.heading) {
      result.push({ id, level: parseInt((b.tag || 'h2').slice(1)), text: b.heading });
    } else if (b['@type'] === 'slate' && b.value?.[0]?.type?.match(/^h[1-6]$/)) {
      const level = parseInt(b.value[0].type.slice(1));
      const text = b.plaintext || b.value[0].children?.map(c => c.text).join('') || '';
      if (text.trim()) result.push({ id, level, text });
    }
  }
  return result;
});
</script>

// docs/examples/examples/svelte/TocBlock.svelte
<script>
  export let block;
  export let content = {};

  $: entries = (() => {
    const result = [];
    if (!content?.blocks || !content?.blocks_layout?.items) return result;
    for (const id of content.blocks_layout.items) {
      const b = content.blocks[id];
      if (!b) continue;
      if (b['@type'] === 'heading' && b.heading) {
        result.push({ id, level: parseInt((b.tag || 'h2').slice(1)), text: b.heading });
      } else if (b['@type'] === 'slate' && b.value?.[0]?.type?.match(/^h[1-6]$/)) {
        const level = parseInt(b.value[0].type.slice(1));
        const text = b.plaintext || b.value[0].children?.map(c => c.text).join('') || '';
        if (text.trim()) result.push({ id, level, text });
      }
    }
    return result;
  })();
</script>

<nav data-block-uid={block['@uid']} class="toc-block">
  {#if entries.length > 0}
    <ul>
      {#each entries as e (e.id)}
        <li style="margin-left: {(e.level - 2) * 1.5}em">
          <a href="#{e.id}">{e.text}</a>
        </li>
      {/each}
    </ul>
  {:else}
    <p>Table of Contents</p>
  {/if}
</nav>
