// docs/blocks/examples/vue/ColumnsBlock.vue
<template>
  <div :data-block-uid="block['@uid']" class="columns-block">
    <div style="display: flex; gap: 1rem">
      <ColumnBlock
        v-for="id in block.columns?.items || []"
        :key="id"
        :block="{ ...block.columns.blocks[id], '@uid': id }"
      />
    </div>
  </div>
</template>

<script setup>
defineProps({ block: Object });
</script>

// docs/blocks/examples/svelte/ColumnsBlock.svelte
<script>
  import ColumnBlock from './ColumnBlock.svelte';
  export let block;
</script>

<div data-block-uid={block['@uid']} class="columns-block">
  <div style="display: flex; gap: 1rem">
    {#each block.columns?.items || [] as id (id)}
      <ColumnBlock block={{ ...block.blocks?.[id], '@uid': id }} />
    {/each}
  </div>
</div>
