// docs/blocks/examples/vue/ImageBlock.vue
<template>
  <div :data-block-uid="block['@uid']">
    <a v-if="href" :href="href" data-edit-link="href">
      <img data-edit-media="url" :src="block.url" :alt="block.alt" />
    </a>
    <img v-else data-edit-media="url" :src="block.url" :alt="block.alt" />
  </div>
</template>

<script setup>
import { computed } from 'vue';
const props = defineProps({ block: Object });
const href = computed(() => props.block.href?.[0]?.['@id'] || props.block.href);
</script>

// docs/blocks/examples/svelte/ImageBlock.svelte
<script>
  export let block;
  $: href = block.href?.[0]?.['@id'] || block.href;
</script>

<div data-block-uid={block['@uid']}>
  {#if href}
    <a {href} data-edit-link="href">
      <img data-edit-media="url" src={block.url} alt={block.alt} />
    </a>
  {:else}
    <img data-edit-media="url" src={block.url} alt={block.alt} />
  {/if}
</div>
